fix unsetting exhibition_id in ImportItemsJob
SlovakNationalGallery/atlas.sng.sk pull request #158
Opened 2023-06-28 09:32 UTC by igor-kamil

2023-06-28 12:41 UTC, FrantisekMichalSebestyen requested changes

2023-06-28 12:41 UTC, FrantisekMichalSebestyen commented on app/Jobs/ImportItemsJob.php
> +        $all_exhibition_ids = Exhibition::all()->pluck('id');
I kind of expect `exhibition_ids` to be equal to `all_exhibition_ids`.
Why is it important to rename this?

2023-06-29 10:20 UTC, eronisko commented on app/Jobs/ImportItemsJob.php
>              }
This check feels a little surprising to me, but I think it's fine either way.

```suggestion
            if (!$item->code) return;
            $item->code->exhibition_id = $exhibition_id;
            $item->code->save();
```

2023-06-30 06:07 UTC, eronisko approved these changes
lgtm

2023-06-30 06:08 UTC, merged