Nsng 97 video in story
SlovakNationalGallery/atlas.sng.sk pull request #82
Opened 2022-12-06 02:16 UTC by igor-kamil

<img width="329" alt="Snímka obrazovky 2022-12-06 o 3 16 07" src="https://user-images.githubusercontent.com/2682941/205792211-cf63b476-b33b-4a11-9fac-3cd2be3d26de.png">

<img width="324" alt="Snímka obrazovky 2022-12-06 o 3 16 15" src="https://user-images.githubusercontent.com/2682941/205792218-f33c994a-574c-4bf1-8760-3ddbcb6e6ad4.png">

2022-12-06 09:27 UTC, rastislav-chynoransky requested changes

2022-12-06 09:27 UTC, rastislav-chynoransky commented on resources/js/components/StoryVideoLightbox.vue
> +            <div class="absolute cursor-pointer p-1 top-0 right-0 bg-white rounded-tr-xl" @click.stop="visible = false">
Change to `button` to make it accessible

2022-12-06 09:27 UTC, rastislav-chynoransky commented on resources/js/components/StoryVideoLightbox.vue
> +        <div class="relative max-h-full w-full md:max-w-lg mx-4" @click.stop="visible = false">
`max-h-full` here is not really working. Also why the click callback here?

2022-12-06 09:27 UTC, rastislav-chynoransky commented on resources/js/components/StoryVideoLightbox.vue
> +    <div class="fixed inset-0 z-50 flex justify-center items-center" v-if="visible" @click="visible = false">
This flex container has only two direct children and the first one is absolute positioned, I'd move the container deeper.

2022-12-06 09:27 UTC, rastislav-chynoransky commented on resources/js/components/InteractionStory.vue
> +        <div class="my-4 relative" v-if="story.video_embed">
I'd move the `relative` class inside `StoryVideoLightbox` as that's its responsibility.

2022-12-06 09:27 UTC, rastislav-chynoransky commented on resources/js/components/StoryVideoLightbox.vue
> +    <a href="#" @click.prevent="visible = true">
Also this link has to be disabled when the `InteractionStory` has `active === true` prop.

2022-12-06 12:26 UTC, igor-kamil commented on resources/js/components/StoryVideoLightbox.vue
> +            class="bg-green rounded-xl px-3 py-2 bottom-3 right-3 absolute flex items-center appearance-none text-[16px] text-black font-medium">
definitely! I was just thinking about that, when I was writing this

2022-12-06 13:26 UTC, rastislav-chynoransky commented on resources/js/components/ItemImageLightbox.vue
> +    <div role="link" class="relative" @click.prevent="visible = true">
```suggestion
    <div role="link" class="relative" @click="visible = true">
```

2022-12-06 13:28 UTC, rastislav-chynoransky commented on resources/js/components/StoryVideoLightbox.vue
> +    <div class="fixed inset-0 z-50 flex justify-center items-center" v-if="visible" @click="visible = false">
```suggestion
    <div class="fixed inset-0 z-50 flex justify-center items-center" v-if="visible">
```

2022-12-06 13:30 UTC, igor-kamil commented on resources/js/components/StoryVideoLightbox.vue
> +    <div class="fixed inset-0 z-50 flex justify-center items-center" v-if="visible" @click="visible = false">
I think it's good to close lightbox also by clicking "outside" (also the same behaviour is used in ItemImageLightbox)

2022-12-07 08:29 UTC, igor-kamil commented on resources/js/components/StoryVideoLightbox.vue
> +    <div role="link" class="relative" @click="active && (visible = true)">
I was thinking about it. First I wanted to make it possible to open video anytime. 
Anyway - I think this is a broader topic. Keep it consistent. If story has inactive byttons - keep it all inactive. 
Sooner or later we shoul make it possible to return back to stroy imho.

2022-12-07 10:38 UTC, rastislav-chynoransky commented on resources/js/components/StoryVideoLightbox.vue
> +    <div role="link" class="relative" @click="active && (visible = true)">
Without the lowered opacity it will appear broken, but I can do it in the recoloring branch.

2022-12-07 10:39 UTC, rastislav-chynoransky requested changes
Please resolve conflicts and it's good to go.

2022-12-07 11:45 UTC, merged